---
- name: Install docker-compose
  apt:
    name: docker-compose
    state: present

- name: Copy docker-compose.yml
  template:
    src: elk/templates/docker-compose.yml.j2
    dest: ./docker-compose/docker-compose.yml

- name: Start ELK
  docker_compose:
    project_src: ./docker-compose
    state: present
    debug: true